---
title: "C5 - ggplot2 - displaying dist."
author: "Rice"
date: "2023-07-28"
output: html_document
---

```{r}
dim(diamonds)
depth_dist <- ggplot(diamonds, aes(depth)) + xlim(58,68) # produces a blank background 
depth_dist


```
```{r}
depth_dist + geom_histogram(aes(y=..density..), binwidth = 0.1) + facet_grid(cut~.)
```
```{r}
depth_dist + geom_histogram(aes(fill=cut),binwidth=0.1, position = "fill")

```
```{r}
depth_dist + geom_freqpoly(aes(y=..density..,color=cut),binwidth=0.1)
```
```{r}
qplot(cut,depth,data=diamonds,geom="boxplot")

```
```{r}
library(ggplot2)
library(plyr)  # needed for the round_any function 

# groups the data by rounded values of "carat" to the nearest tenth using the round_any() function from the plyr package

qplot(carat,depth,data=diamonds,geom="boxplot",group=round_any(carat,0.5,floor),xlim=c(0,3))
```
```{r}

## geom jitter - a crude way of looking at discrete distributions by adding random noise to the discrete values so they do not overplot 

qplot(class, cty, data=mpg,geom="jitter")
qplot(class, drv,data=mpg,geom="jitter")

```

